### ISSUE TITLE
Interact with COM port

### ISSUE THREAD

**Issue by TaylorTWBrown** [firejox/WinSocat#1]
I love this, but one feature that I miss from socat is the ability to interact with local serial ports. Serial to TCP is particularly useful.

`socat pty,link=/dev/ttyS0,raw tcp:127.0.0.1:60001& `

Is this already possible with WinSocat, or could it be added as a feature?

**Comment by firejox** [comment]
Currently `winsocat` does not support serial port interaction, but it can be added as a feature in future. I'm not familiar with how serial port work, so it requires some time to implement it.

**Comment by TaylorTWBrown** [comment]
I'd love serial port support - my main use case is sharing serial ports from physical to VM. I've been using Cygwin's socat, but it's a bit janky.

I'll have to brush up on my C# and lend a hand :)

**Comment by firejox** [comment]
Now, pre-release [v0.1.3-rc1](https://github.com/firejox/WinSocat/releases/tag/v0.1.3-rc1) support serial port relaying. You can try whether it meets in your use case. Any problem is welcome to report.

**Comment by firejox** [comment]
Close due to this feature existing in release [v0.1.3](https://github.com/firejox/WinSocat/releases/tag/v0.1.3).
