### ISSUE TITLE
Winget support

### ISSUE THREAD

**Issue by beriberikix** [firejox/WinSocat#4]
Hello! Thank you for this project. Have you considered adding [Winget](https://learn.microsoft.com/en-us/windows/package-manager/winget/) support for distribution? It's become rather popular.

**Comment by firejox** [comment]
Sure. I would take time to add that distribution recently.

**Comment by firejox** [comment]
It has been merged in https://github.com/microsoft/winget-pkgs/pull/107897.
You can install `winsocat` now by running:
```
winget install -e --id Firejox.WinSocat
```

If there is any problem, please let me know.

**Comment by beriberikix** [comment]
That was fast! The install worked perfectly but `winsocket.exe` wasn't added to the system environment variable. Would it be configure that as well?

**Comment by firejox** [comment]
@beriberikix `winget` will setup the `PATH` variable, but it will not change the variable in current terminal. Restarting the terminal will resolve the problem.

**Comment by beriberikix** [comment]
That was it, thanks! Appreciate the fast implementation.
